# Program Name: statistical_significance_test.py
# Version: 1.0 (Final Submission)
# Description: Computes Welch's t-test to verify the statistical significance
#              of the accuracy trade-off between the Proposed NMF method and 
#              the CNN baseline across 5 cross-validation folds.
#
# Prerequisites:
#   - Must run `nmf_crossval_divergence.py` first to generate `cv_results.npz`

import numpy as np
from scipy import stats
import os

from google.colab import drive
drive.mount('/content/drive')

# 1. Load CNN Baseline 5-Fold Accuracies
# These were generated by cnn_baseline_study.py
cnn_fold_accs = [0.89139633, 0.92090395, 0.91949153, 0.88983051, 0.89124294]

# 2. Load Proposed Method 5-Fold Accuracies
# These are loaded dynamically from the saved cross-validation run
cv_file = 'cv_results.npz'
if not os.path.exists(cv_file):
    # Fallback to drive path if running in Colab
    cv_file = '/content/drive/MyDrive/PhysioNet2016/cv_results.npz'

if os.path.exists(cv_file):
    data = np.load(cv_file)
    nmf_fold_accs = data['fold_acc']
else:
    print("Error: Could not find cv_results.npz. Please run the cross-validation script first.")
    exit()

print("=== Statistical Significance Test (Welch's t-test) ===")
print(f"CNN Baseline Fold Accuracies : {np.round(cnn_fold_accs, 4)}")
print(f"Proposed NMF Fold Accuracies : {np.round(nmf_fold_accs, 4)}")

# 3. Compute Welch's t-test 
# equal_var=False ensures it is Welch's t-test, which does not assume equal population variances
t_stat, p_val = stats.ttest_ind(cnn_fold_accs, nmf_fold_accs, equal_var=False)

print("\n--- Results ---")
print(f"CNN Mean Accuracy: {np.mean(cnn_fold_accs)*100:.2f}%")
print(f"NMF Mean Accuracy: {np.mean(nmf_fold_accs)*100:.2f}%")
print(f"Trade-off Gap    : {(np.mean(cnn_fold_accs) - np.mean(nmf_fold_accs))*100:.2f}%")
print(f"p-value          : {p_val:.4e}")

if p_val < 0.01:
    print("\nConclusion: The accuracy difference IS statistically significant (p < 0.01).")
else:
    print("\nConclusion: The accuracy difference is NOT statistically significant.")